# Generated by Django 5.1.1 on 2024-10-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remove_delivery_order_id_delivery_delivery_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryperson',
            name='is_available',
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='last_dispatched',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
