# Generated by Django 5.1.1 on 2024-10-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remove_delivery_estimated_delivery_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryperson',
            old_name='delivery_address',
            new_name='postal_area',
        ),
    ]
