# Generated by Django 5.1.1 on 2024-10-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_remove_deliveryperson_is_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='delivery_address',
            new_name='delivery_postal_code',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_process', 'In Process'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
