openapi: 3.0.3
info:
  title: Papa Luigis Delicious Pizza
  version: 1.0.0
  description: We serve digitally delicious flamboyant treats!
paths:
  /api/customers/login/:
    post:
      operationId: customers_login_create
      tags:
      - customers
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/customers/register/:
    post:
      operationId: customers_register_create
      tags:
      - customers
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/menu/ingredient/:
    get:
      operationId: menu_ingredient_list
      tags:
      - menu
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ingredient'
          description: ''
  /api/menu/ingredient/{id}/:
    get:
      operationId: menu_ingredient_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this ingredient.
        required: true
      tags:
      - menu
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
          description: ''
  /api/menu/menuItem/:
    get:
      operationId: menu_menuItem_list
      parameters:
      - in: query
        name: type
        schema:
          type: string
      tags:
      - menu
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MenuItem'
          description: ''
  /api/menu/menuItem/{id}/:
    get:
      operationId: menu_menuItem_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this menu item.
        required: true
      tags:
      - menu
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuItem'
          description: ''
  /api/menu/pizza/:
    get:
      operationId: menu_pizza_list
      tags:
      - menu
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pizza'
          description: ''
  /api/menu/pizza/{pizza_id}/:
    get:
      operationId: menu_pizza_retrieve
      parameters:
      - in: path
        name: pizza_id
        schema:
          type: integer
        description: A unique integer value identifying this pizza.
        required: true
      tags:
      - menu
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pizza'
          description: ''
  /api/orders/earnings/:
    get:
      operationId: orders_earnings_retrieve
      tags:
      - orders
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/orders/order/:
    get:
      operationId: orders_order_list
      parameters:
      - in: query
        name: status
        schema:
          type: string
      tags:
      - orders
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
          description: ''
    post:
      operationId: orders_order_create
      tags:
      - orders
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Order'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Order'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: ''
  /api/orders/order/{id}/:
    get:
      operationId: orders_order_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this order.
        required: true
      tags:
      - orders
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: ''
    put:
      operationId: orders_order_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this order.
        required: true
      tags:
      - orders
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Order'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Order'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: ''
    patch:
      operationId: orders_order_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this order.
        required: true
      tags:
      - orders
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedOrder'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedOrder'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedOrder'
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: ''
    delete:
      operationId: orders_order_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this order.
        required: true
      tags:
      - orders
      security:
      - jwtAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/token/refresh/:
    post:
      operationId: token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
components:
  schemas:
    Dessert:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 30
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,5}(?:\.\d{0,3})?$
        menu_item:
          type: integer
      required:
      - id
      - menu_item
      - name
      - price
    Drink:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 30
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,5}(?:\.\d{0,3})?$
        menu_item:
          type: integer
      required:
      - id
      - menu_item
      - name
      - price
    Ingredient:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 30
        cost:
          type: string
          format: decimal
          pattern: ^-?\d{0,5}(?:\.\d{0,3})?$
        is_vegetarian:
          type: boolean
      required:
      - cost
      - id
      - name
    MenuItem:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        desserts:
          type: array
          items:
            $ref: '#/components/schemas/Dessert'
        drinks:
          type: array
          items:
            $ref: '#/components/schemas/Drink'
        pizzas:
          type: array
          items:
            $ref: '#/components/schemas/Pizza'
        name:
          type: string
          maxLength: 30
        type:
          type: string
          maxLength: 20
      required:
      - desserts
      - drinks
      - id
      - name
      - pizzas
      - type
    Order:
      type: object
      properties:
        customer_id:
          type: integer
        order_date:
          type: string
          format: date
        status:
          type: string
          maxLength: 50
        total_price:
          type: string
          format: decimal
          pattern: ^-?\d{0,5}(?:\.\d{0,3})?$
        discount_applied:
          type: boolean
        delivery_address:
          type: string
          maxLength: 30
        order_menu_items:
          type: array
          items:
            $ref: '#/components/schemas/OrderMenuItem'
        estimated_delivery_time:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
      required:
      - customer_id
      - delivery_address
      - order_date
      - order_menu_items
      - status
      - total_price
    OrderMenuItem:
      type: object
      properties:
        menu_item_id:
          type: integer
        quantity:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        extra_ingredients:
          type: array
          items:
            $ref: '#/components/schemas/OrderMenuItemExtraIngredient'
      required:
      - menu_item_id
      - quantity
    OrderMenuItemExtraIngredient:
      type: object
      properties:
        ingredient_id:
          type: integer
        quantity:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
      required:
      - ingredient_id
      - quantity
    PatchedOrder:
      type: object
      properties:
        customer_id:
          type: integer
        order_date:
          type: string
          format: date
        status:
          type: string
          maxLength: 50
        total_price:
          type: string
          format: decimal
          pattern: ^-?\d{0,5}(?:\.\d{0,3})?$
        discount_applied:
          type: boolean
        delivery_address:
          type: string
          maxLength: 30
        order_menu_items:
          type: array
          items:
            $ref: '#/components/schemas/OrderMenuItem'
        estimated_delivery_time:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
          nullable: true
    Pizza:
      type: object
      properties:
        pizza_id:
          type: integer
          readOnly: true
        ingredients:
          type: string
          readOnly: true
        base_id:
          $ref: '#/components/schemas/PizzaBase'
        price:
          type: string
          readOnly: true
        vegan:
          type: string
          readOnly: true
        name:
          type: string
          maxLength: 30
        time_to_cook:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        user_id:
          type: integer
          nullable: true
        menu_item_id:
          type: integer
      required:
      - base_id
      - ingredients
      - menu_item_id
      - name
      - pizza_id
      - price
      - time_to_cook
      - vegan
    PizzaBase:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 30
        cost:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        is_vegetarian:
          type: boolean
      required:
      - cost
      - id
      - name
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
