openapi: 3.0.3
info:
  title: Papa Luigis Delicious Pizza
  version: 1.0.0
  description: We serve digitally delicious flamboyant treats!
paths:
  /customers/login/:
    post:
      operationId: customers_login_create
      tags:
      - customers
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /customers/metrics/:
    post:
      operationId: customers_metrics_create
      tags:
      - customers
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /customers/preferences/:
    get:
      operationId: customers_preferences_retrieve
      tags:
      - customers
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: customers_preferences_create
      tags:
      - customers
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /customers/register/:
    post:
      operationId: customers_register_create
      tags:
      - customers
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /menu/ingredient/:
    get:
      operationId: menu_ingredient_list
      tags:
      - menu
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ingredient'
          description: ''
  /menu/ingredient/{id}/:
    get:
      operationId: menu_ingredient_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this ingredient.
        required: true
      tags:
      - menu
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
          description: ''
  /menu/menuItem/:
    get:
      operationId: menu_menuItem_list
      parameters:
      - in: query
        name: type
        schema:
          type: string
      tags:
      - menu
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MenuItem'
          description: ''
  /menu/menuItem/{id}/:
    get:
      operationId: menu_menuItem_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this menu item.
        required: true
      tags:
      - menu
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuItem'
          description: ''
  /menu/pizza/:
    get:
      operationId: menu_pizza_list
      tags:
      - menu
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pizza'
          description: ''
  /menu/pizza/{pizza_id}/:
    get:
      operationId: menu_pizza_retrieve
      parameters:
      - in: path
        name: pizza_id
        schema:
          type: integer
        description: A unique integer value identifying this pizza.
        required: true
      tags:
      - menu
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pizza'
          description: ''
  /orders/add-item-to-order/:
    post:
      operationId: orders_add_item_to_order_create
      tags:
      - orders
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /orders/earnings/:
    get:
      operationId: orders_earnings_retrieve
      tags:
      - orders
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /orders/orders/{id}/finalize/:
    post:
      operationId: orders_orders_finalize_create
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - orders
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /token/refresh/:
    post:
      operationId: token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
components:
  schemas:
    Dessert:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 30
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,5}(?:\.\d{0,3})?$
        menu_item:
          type: integer
      required:
      - id
      - menu_item
      - name
      - price
    Drink:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 30
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,5}(?:\.\d{0,3})?$
        menu_item:
          type: integer
      required:
      - id
      - menu_item
      - name
      - price
    Ingredient:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 30
        cost:
          type: string
          format: decimal
          pattern: ^-?\d{0,5}(?:\.\d{0,3})?$
        is_vegetarian:
          type: boolean
      required:
      - cost
      - id
      - name
    MenuItem:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        desserts:
          type: array
          items:
            $ref: '#/components/schemas/Dessert'
        drinks:
          type: array
          items:
            $ref: '#/components/schemas/Drink'
        pizzas:
          type: array
          items:
            $ref: '#/components/schemas/Pizza'
        name:
          type: string
          maxLength: 30
        type:
          type: string
          maxLength: 20
      required:
      - desserts
      - drinks
      - id
      - name
      - pizzas
      - type
    Pizza:
      type: object
      properties:
        pizza_id:
          type: integer
          readOnly: true
        ingredients:
          type: string
          readOnly: true
        base_id:
          $ref: '#/components/schemas/PizzaBase'
        price:
          type: string
          readOnly: true
        vegan:
          type: string
          readOnly: true
        name:
          type: string
          maxLength: 30
        time_to_cook:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        user_id:
          type: integer
          nullable: true
        menu_item_id:
          type: integer
      required:
      - base_id
      - ingredients
      - menu_item_id
      - name
      - pizza_id
      - price
      - time_to_cook
      - vegan
    PizzaBase:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 30
        cost:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        is_vegetarian:
          type: boolean
      required:
      - cost
      - id
      - name
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
