openapi: 3.0.3
info:
  title: Papa Luigis Delicious Pizza
  version: 1.0.0
  description: We serve digitally delicious flamboyant treats!
paths:
  /customers/login/:
    post:
      operationId: customers_login_create
      tags:
      - customers
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /customers/metrics/:
    post:
      operationId: customers_metrics_create
      tags:
      - customers
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /customers/preferences/:
    get:
      operationId: customers_preferences_retrieve
      tags:
      - customers
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: customers_preferences_create
      tags:
      - customers
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /customers/register/:
    post:
      operationId: customers_register_create
      tags:
      - customers
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /menu/ingredientlist/:
    get:
      operationId: menu_ingredientlist_retrieve
      tags:
      - menu
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /menu/pizzalist/:
    get:
      operationId: menu_pizzalist_retrieve
      tags:
      - menu
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /orders/add-item/:
    post:
      operationId: orders_add_item_create
      tags:
      - orders
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /orders/earnings/:
    get:
      operationId: orders_earnings_retrieve
      tags:
      - orders
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /orders/finalize/:
    post:
      operationId: orders_finalize_create
      tags:
      - orders
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /orders/items/:
    get:
      operationId: orders_items_retrieve
      tags:
      - orders
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /orders/remove-item/:
    post:
      operationId: orders_remove_item_create
      tags:
      - orders
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /token/refresh/:
    post:
      operationId: token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
components:
  schemas:
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
