# Generated by Django 5.1.1 on 2024-10-05 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('discount_code_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=11)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=8)),
                ('description', models.CharField(max_length=100)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('expiration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('total_pizzas_ordered', models.IntegerField(default=0)),
                ('is_birthday_freebie', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('customer_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_line', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPreferences',
            fields=[
                ('customer_preferences_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_vegetarian', models.BooleanField()),
                ('is_vegan', models.BooleanField()),
                ('is_spicy', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='customers.customer')),
            ],
        ),
    ]
