# Generated by Django 5.1.1 on 2024-10-06 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('discount_code_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=11)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=8)),
                ('description', models.CharField(max_length=100)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('expiration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('address_line', models.CharField(blank=True, max_length=30, null=True)),
                ('postal_code', models.CharField(default=0, max_length=20)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('total_pizzas_ordered', models.IntegerField(default=0)),
                ('is_birthday_freebie', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('customer_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('average_order_time', models.FloatField(blank=True, help_text='Average order time in seconds', null=True)),
                ('pizza_info_clicks', models.IntegerField(default=0, help_text='Number of times user clicked on pizza info')),
                ('scroll_deepness', models.IntegerField(blank=True, help_text='Scroll depth as an integer', null=True)),
                ('abandoned_customization_times', models.IntegerField(default=0, help_text='Times the user abandoned customization')),
                ('times_ingredient_removed', models.JSONField(default=dict, help_text='Dictionary of ingredients and times removed')),
                ('times_pizza_ordered', models.JSONField(default=dict, help_text='Dictionary of pizzas and times they were ordered')),
                ('avg_pizza_rating', models.JSONField(default=dict, help_text='Dictionary of pizzas and their average ratings')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPreferences',
            fields=[
                ('customer_preferences_id', models.AutoField(primary_key=True, serialize=False)),
                ('pizza_base', models.IntegerField(choices=[(0, 'Thin Crust'), (1, 'Thick Crust'), (2, 'Gluten-Free'), (3, 'Regular')])),
                ('favourite_sauce', models.IntegerField(choices=[(0, 'Tomato'), (1, 'Pesto'), (2, 'White Sauce')])),
                ('cheese_preference', models.IntegerField(choices=[(0, 'Mozzarella'), (1, 'Cheddar'), (2, 'No Cheese'), (3, 'Vegan Cheese')])),
                ('topping_pepperoni', models.BooleanField(default=False)),
                ('topping_mushrooms', models.BooleanField(default=False)),
                ('topping_onions', models.BooleanField(default=False)),
                ('topping_olives', models.BooleanField(default=False)),
                ('topping_bell_peppers', models.BooleanField(default=False)),
                ('topping_chicken', models.BooleanField(default=False)),
                ('spiciness_level', models.IntegerField(choices=[(0, 'Mild'), (1, 'Medium'), (2, 'Spicy')])),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('pizza_size', models.IntegerField(choices=[(0, 'Small'), (1, 'Medium'), (2, 'Large')])),
                ('budget_range', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='customers.customer')),
            ],
        ),
    ]
