# Generated by Django 5.1.1 on 2024-10-05 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customerpreferences',
            name='is_spicy',
        ),
        migrations.AddField(
            model_name='customer',
            name='address_line',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='budget_range',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='cheese_preference',
            field=models.IntegerField(choices=[(0, 'Mozzarella'), (1, 'Cheddar'), (2, 'No Cheese'), (3, 'Vegan Cheese')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='favourite_sauce',
            field=models.IntegerField(choices=[(0, 'Tomato'), (1, 'Pesto'), (2, 'White Sauce')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='is_gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='pizza_base',
            field=models.IntegerField(choices=[(0, 'Thin Crust'), (1, 'Thick Crust'), (2, 'Gluten-Free'), (3, 'Regular')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='pizza_size',
            field=models.IntegerField(choices=[(0, 'Small'), (1, 'Medium'), (2, 'Large')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='spiciness_level',
            field=models.IntegerField(choices=[(0, 'Mild'), (1, 'Medium'), (2, 'Spicy')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='topping_bell_peppers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='topping_chicken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='topping_mushrooms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='topping_olives',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='topping_onions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='topping_pepperoni',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customerpreferences',
            name='is_vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customerpreferences',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('customer_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('average_order_time', models.FloatField(blank=True, help_text='Average order time in seconds', null=True)),
                ('pizza_info_clicks', models.IntegerField(default=0, help_text='Number of times user clicked on pizza info')),
                ('scroll_deepness', models.IntegerField(blank=True, help_text='Scroll depth as an integer', null=True)),
                ('abandoned_customization_times', models.IntegerField(default=0, help_text='Times the user abandoned customization')),
                ('times_ingredient_removed', models.JSONField(default=dict, help_text='Dictionary of ingredients and times removed')),
                ('times_pizza_ordered', models.JSONField(default=dict, help_text='Dictionary of pizzas and times they were ordered')),
                ('avg_pizza_rating', models.JSONField(default=dict, help_text='Dictionary of pizzas and their average ratings')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='customers.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
    ]
