# Generated by Django 5.1.1 on 2024-10-05 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_discountcode_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPreferences',
            fields=[
                ('customer_preferences_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_vegetarian', models.BooleanField()),
                ('is_vegan', models.BooleanField()),
                ('is_spicy', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='customers.customer')),
            ],
        ),
    ]
