# Generated by Django 5.1.1 on 2024-10-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='discount_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='discount_code',
            field=models.CharField(default=1, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
