# Generated by Django 5.1.1 on 2024-10-08 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_delete_discountcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('customer_preferences_id', models.AutoField(primary_key=True, serialize=False)),
                ('favourite_sauce', models.IntegerField(choices=[(0, 'Tomato'), (1, 'Pesto'), (2, 'White Sauce')])),
                ('cheese_preference', models.IntegerField(choices=[(0, 'Mozzarella'), (1, 'Cheddar'), (2, 'No Cheese'), (3, 'Vegan Cheese')])),
                ('pepperoni', models.IntegerField(default=0)),
                ('mushrooms', models.IntegerField(default=0)),
                ('onions', models.IntegerField(default=0)),
                ('olives', models.IntegerField(default=0)),
                ('sun_dried_tomatoes', models.IntegerField(default=0)),
                ('bell_peppers', models.IntegerField(default=0)),
                ('chicken', models.IntegerField(default=0)),
                ('bacon', models.IntegerField(default=0)),
                ('ham', models.IntegerField(default=0)),
                ('sausage', models.IntegerField(default=0)),
                ('ground_beef', models.IntegerField(default=0)),
                ('anchovies', models.IntegerField(default=0)),
                ('pineapple', models.IntegerField(default=0)),
                ('basil', models.IntegerField(default=0)),
                ('broccoli', models.IntegerField(default=0)),
                ('zucchini', models.IntegerField(default=0)),
                ('garlic', models.IntegerField(default=0)),
                ('jalapenos', models.IntegerField(default=0)),
                ('BBQ_sauce', models.IntegerField(default=0)),
                ('red_peppers', models.IntegerField(default=0)),
                ('spinach', models.IntegerField(default=0)),
                ('feta_cheese', models.IntegerField(default=0)),
                ('spiciness_level', models.IntegerField(choices=[(0, 'Mild'), (1, 'Medium'), (2, 'Spicy')])),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('pizza_size', models.IntegerField(choices=[(0, 'Small'), (1, 'Medium'), (2, 'Large')])),
                ('budget_range', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerPreferences',
        ),
    ]
