# Generated by Django 5.1.1 on 2024-10-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_userpreferences_delete_customerpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='budget_range',
            field=models.IntegerField(default=7),
        ),
    ]
