# Generated by Django 5.1.1 on 2024-10-12 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customerpreferences_delete_userpreferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdata',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerdata',
            name='customer_data_id',
        ),
        migrations.RemoveField(
            model_name='customerpreferences',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerpreferences',
            name='customer_preferences_id',
        ),
        migrations.AddField(
            model_name='customerdata',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='data', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile1', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
