# Generated by Django 5.1.1 on 2024-10-12 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_remove_customerdata_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customerdata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customerpreferences',
            name='id',
        ),
        migrations.AddField(
            model_name='customerdata',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='customers.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdata',
            name='customer_data_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='customer_preferences_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
