# Generated by Django 5.1.1 on 2024-10-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_remove_customerdata_id_remove_customerdata_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='discount_code',
            field=models.CharField(max_length=32),
        ),
    ]
