# Generated by Django 5.1.1 on 2024-10-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_alter_customerpreferences_bbq_sauce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpreferences',
            name='budget_range',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=8),
        ),
    ]
