# Generated by Django 5.1.1 on 2024-10-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_alter_customerpreferences_budget_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpreferences',
            name='budget_range',
            field=models.FloatField(default=0),
        ),
    ]
