# Generated by Django 5.1.1 on 2024-10-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_alter_customerpreferences_budget_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpreferences',
            name='budget_range',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=8),
        ),
        migrations.DeleteModel(
            name='CustomerData',
        ),
    ]
