# Generated by Django 5.1.1 on 2024-10-17 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_alter_customerpreferences_budget_range_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerpreferences',
            old_name='budget_range',
            new_name='max_budget',
        ),
    ]
