# Generated by Django 5.1.1 on 2024-09-14 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Desert',
            new_name='Dessert',
        ),
    ]
