# Generated by Django 5.1.1 on 2024-10-06 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='base_id',
            new_name='base',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='menu_item_id',
            new_name='menu_item',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='user_id',
            new_name='user',
        ),
    ]
