# Generated by Django 5.1.1 on 2024-10-06 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_base_id_pizza_base_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='base',
            new_name='base_id',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='menu_item',
            new_name='menu_item_id',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='user',
            new_name='user_id',
        ),
    ]
