# Generated by Django 5.1.1 on 2024-09-15 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_desert_dessert'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='time_to_cook',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dessert',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desserts', to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='menu_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='menu.menuitem'),
        ),
    ]
