# Generated by Django 5.1.1 on 2024-10-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_userpizzarating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='pizza_id',
            new_name='id',
        ),
    ]
