# Generated by Django 5.1.1 on 2024-10-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rename_pizza_id_pizza_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='id',
            new_name='pizza_id',
        ),
    ]
