# Generated by Django 5.1.1 on 2024-10-12 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_rename_id_pizza_pizza_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dessert',
            old_name='dessert_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='drink_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='pizza_id',
            new_name='id',
        ),
    ]
