# Generated by Django 5.1.1 on 2024-10-12 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_rename_dessert_id_dessert_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vegan', models.DecimalField(decimal_places=3, max_digits=8)),
                ('is_vegetarian', models.DecimalField(decimal_places=3, max_digits=8)),
                ('spicy', models.DecimalField(decimal_places=3, max_digits=8)),
                ('is_meat', models.DecimalField(decimal_places=3, max_digits=8)),
                ('is_vegetable', models.DecimalField(decimal_places=3, max_digits=8)),
                ('cheesy', models.DecimalField(decimal_places=3, max_digits=8)),
                ('sweet', models.DecimalField(decimal_places=3, max_digits=8)),
                ('salty', models.DecimalField(decimal_places=3, max_digits=8)),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu.ingredient')),
            ],
        ),
    ]
