# Generated by Django 5.1.1 on 2024-10-06 21:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('total_price', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=8)),
                ('discount_applied', models.BooleanField(default=False)),
                ('delivery_address', models.CharField(max_length=255)),
                ('estimated_delivery_time', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
