# Generated by Django 5.1.1 on 2024-10-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermenuitem',
            name='menu_item',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='open', max_length=50),
        ),
    ]
