# Generated by Django 5.1.1 on 2024-10-06 21:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermenuitemextraingredient',
            name='order_menu_item',
        ),
        migrations.RemoveField(
            model_name='ordermenuitemextraingredient',
            name='ingredient',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.DeleteModel(
            name='OrderMenuItem',
        ),
        migrations.DeleteModel(
            name='OrderMenuItemExtraIngredient',
        ),
    ]
