# Generated by Django 5.1.1 on 2024-10-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='freebie_applied',
            field=models.BooleanField(default=False),
        ),
    ]
