# Generated by Django 5.1.1 on 2024-10-12 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_discount_applied_order_reedemable_discount_applied_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='reedemable_discount_applied',
            new_name='redeemable_discount_applied',
        ),
    ]
