# Generated by Django 5.1.1 on 2024-10-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_reedemable_discount_applied_order_redeemable_discount_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
