# Generated by Django 5.1.1 on 2024-10-14 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_rename_delivery_person_id_delivery_delivery_person_and_more'),
        ('orders', '0010_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='delivery.delivery'),
        ),
    ]
