# Generated by Django 5.1.1 on 2024-10-15 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_alter_customer_discount_code'),
        ('orders', '0011_alter_order_delivery'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('customer', 'status')},
        ),
    ]
